#nginx
#支持私库

#支持指定架构
#--platform=linux/arm64 xiaoyaliu/alist

#milvusdb/milvus:v2.5.12

#milvusdb/milvus-config-tool:v0.1.2
#milvusdb/heaptrack:v0.1.0

#milvusdb/etcd:3.5.18-r1

#apachepulsar/pulsar:3.0.7
#apachepulsar/pulsar:2.9.5
#bitnami/kubectl:latest
#zilliz/attu:v2.5

#pingcap/pd:v8.4.0
#pingcap/tikv:v8.4.0
#pingcap/tidb:v8.4.0

alpine:3.19.1



